Target-template alignment
>P1;SRC_HUMAN_D0
sequence:SRC_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRLEVKLGQGCFGEVWMGTWNGTTRV-AIKTLKPGTMSPEA----FLQEAQVMKKLRHEKLVQL-YAVVSEEPIYIVTEYMSKGSLL------DFLKGETGKYLRLPQLVDMAAQIASGMAYVERMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNEYTARQGAKFPIKWTAPEAALYGRFTIKSDVWSFGILLTELTTKGRVPYPGMVNREVLDQV---ERGYRMPCPPECPESLHDLMCQCWRKEPEER----PTFEYLQAFLEDYF*
>P1;AKT2_HUMAN_D0_1GZK_A
structureX:AKT2_HUMAN_D0_1GZK_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FDYLKLLGKGTFGKVILVREKATGRYYAMKILRKEVIIAKDEVAHTVTESRVLQNTRHPFLTALKYAFQTHDRLCFVMEYANGGELFFHLSRERVFTEERARFY--------GAEIVSALEYLHSRDVVYRDIKLENLMLDKDGHIKITDFGLCKEGISDGATMKTFCGTP-EYLAPEVLEDNDYGRAVDWWGLGVVMYEMMC-GRLPFYNQDHERLFELILMEEIRFPRTLSPEAKSLLAGLL----KKDPKQRLGGGPS-DAKEVMEHRFF*
