Target-template alignment
>P1;ERBB2_HUMAN_D0
sequence:ERBB2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRKVKVLGSGAFGTVYKGIWIPDGENVKIPVAIKVLRENTSPK-------ANKEILDEAYVMAGVGSPYVSRLLGICLTSTVQLVTQLMPYGCLLDHVRENRGRLGSQDLLNWCMQIAKGMSYLE--------DVRLVHRDLAARNVLVKSPNHVKITDFGLARLLDIDETEYHADGGKVP----IKWMALESILRRRFT-------HQSDVWSYGVTVWELM----------TFGAKPYDGIPA-------REIPDLLEKGERLP-----QPPICTIDVYMIMVKCWMIDSECRPRFRELVSEFSRMARDPQRFV*
>P1;ACVR1_HUMAN_D0_3H9R_A
structureX:ACVR1_HUMAN_D0_3H9R_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
ITLLECVGKGRYGEVWRGSW--QGENV----AVKIFSSRDEKSWFRETELYNTVMLRHENILGFIASDMTSR----HSSTQLWLITHYHEMGSLYDYLQLTT--LDTVSCLRIVLSIASGLAHLHIEIFGTQGKPAIAHRDLKSKNILVKKNGQCCIADLGLAVMHS--QSTNQLDVGNNPRVGTKRYMAPE-VLDETIQVDCFDSYKRVDIWAFGLVLWEVARRMVSNGIVEDYKPPFYDVVPNDPSFEDMRKVVCVDQQRPNIPNRWFSDPTLTSLA--KLMKECWYQNPSAR--LTAL-----RIKKTLTKID*
