Target-template alignment
>P1;EGFR_HUMAN_D0
sequence:EGFR_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
FKKIKVLGSGAFGTVYKGLWIPEGEKVKIPVAIKELREATSPKANKEILDEA--YVMASVDNPHVCRLLGICLTS-----TVQLITQLMPFGCLLDYVREHKDNIGSQYLLNWCVQIAKGMNYLE--------DRRLVHRDLAARNVLVKTPQHVKITDFGLAKLLGAEEKEYHAEGGKVP----IKWMALESILHRIYT------HQSDVWSYGVTVWELM----------TFGSKPYDGIPAS-------EISSILEKGERLP-----QPPICTIDVYMIMVKCWMIDADSRPKFRELIIEFSKMARDPQRYL*
>P1;ACVR1_HUMAN_D0_3H9R_A
structureX:ACVR1_HUMAN_D0_3H9R_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
ITLLECVGKGRYGEVWRGSW--QGENVAVKI--------FSSRDEKSWFRETELYNTVMLRHENILGFIASDMTSRHSSTQLWLITHYHEMGSLYDYLQ--LTTLDTVSCLRIVLSIASGLAHLHIEIFGTQGKPAIAHRDLKSKNILVKKNGQCCIADLGLAVMHSQSTNQLDV--GNNPRVGTKRYMAPEVLDETIQVDCFDSYKRVDIWAFGLVLWEVARRMVSNGIVEDYKPPFYDVVPNDPSFEDMRKVVCVDQQRPNIPNRWFSDPTLTSLA--KLMKECWYQNPSAR-------LTALRIKKTLTKID*
