Target-template alignment
>P1;ERBB2_HUMAN_D0
sequence:ERBB2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRKVKVLGSGAFGTVY------------KGIWIPDGENVKI-PVAIKVLRENTSPKANKEILDEAYVMAGVGSPY-VSRLLGICLTSTV-QLVTQLMPYGCLLDHVRENRGRLGSQDLLNWCMQIAKGMSYLEDVR--LVHRDLAARNVLVKSPNHVKITDFGLA------------RLLDIDETEYHADGGKVPIKWMALESILRRRF-THQSDVWSYGVTVWELMTFGAKPYDGIPAREIPDLLEKGE-RLPQPPICTIDVYMIMVKCWMIDSECRPRFRELVSEFSRMARDPQRFV*
>P1;AAK1_HUMAN_D0_4WSQ_A
structureX:AAK1_HUMAN_D0_4WSQ_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VTVDEVLAEGGFAIVFLVRTSNGMKCALKRMFVNNEHDLQVCKREIQIMRDLSGHKNIVGYIDSSINNVSSGDVWEVLILMDFCRGGQVVNLMNQRLQTG------------FTENEVLQIFCDTCEAVARLHQCKTPIIHRDLKVENILLHDRGHYVLCDFGSATNKFQNPQTEGVNAVEDEIKKYTTLSYRAP----EMVNLYSGKIITTKADIWALGCLLYKLCYFT------LPFGESQVAICDGNFTIPDNSRYSQDMHCLIRYMLEPDPDKRPDIYQ-VSYFS------FKLL*
