Target-template alignment
>P1;ABL1_HUMAN_D0
sequence:ABL1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITMKHKLGGGQYGEVY----EGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQEVNAVVLLYMATQISSAMEYLE-KKNFIHRDLAARNCLVGENHLVKVADFGLSR--LMTGDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYEL-LEKDYRMERPEGCPEKVYELMRACWQWNPSDRPSFAEIHQAFETMFQESSISDEVEKELGKQ--*
>P1;AKT1_HUMAN_D0_3CQU_A
structureX:AKT1_HUMAN_D0_3CQU_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FEYLKLLGKGTFGKVILVKEKATGRYYAMKILKKEVIVAKDEVAHTLTENRVLQNSRHPFLTALKYSFQTHDRLCFVMEYANGGEL--FFHLSRERVFSEDRARFYGAEIVSALDYLHSEKNVVYRDLKLENLMLDKDGHIKITDFGLCKEGIKDGATMKTFCGTP---EYLAPEVLEDNDYGRAVDWWGLGVVMYEM-MCGRLPFYNQDHEKLFELILMEEIRFPRTLG-PE-AKSLLSGLLKKDPKQRLG---------------GGSEDAKEIMQHRFF*
