Target-template alignment
>P1;CSK_HUMAN_D0
sequence:CSK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LKLLQTIGKGEFGDVMLGDYRGNKVAVKCIKNDATAQAFLAEASVMTQ--LRHSNLVQLLGVIVEEKGG---LYIVTEYMAKGSLVDYLRSRGRSVLGGDCLLKFSLDVCEAMEYLEGNNF--------VHRDLAARNVLVSEDNVAKVSDFGLT---KEASSTQDTGKLP----VKWTAPEALREKK----FST--KSDVWSFGILLWEI----YSFGRVPYPRIPLKDVVPR---VEKGYKMDAPDGCPP-------------AVYEVMKNCWHLDAAMRPSFLQLREQLEHIKTHELH*
>P1;ACVR1_HUMAN_D0_3H9R_A
structureX:ACVR1_HUMAN_D0_3H9R_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
ITLLECVGKGRYGEVWRGSWQGENVAVK-IFSSRDEKSWFRETELYNTVMLRHENILGFIASDMTSRHSSTQLWLITHYHEMGSLYDYLQLTTLDTV--SCL-RIVLSIASGLAHLHIEIFGTQGKPAIAHRDLKSKNILVKKNGQCCIADLGLAVMHSQSTNQLDVGNNPRVGTKRYMAPEVLDETIQVDCFDSYKRVDIWAFGLVLWEVARRMVSNGIVEDYKPPFYDVVPNDPSFEDMRKVVCVDQQRPNIPNRWFSDPTLTSLAKLMKECWYQNPSARLTALRIKKTLTKID-----*
