Target-template alignment
>P1;ABL2_HUMAN_D0
sequence:ABL2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITMKHKLGGGQYGEVYVGVWKKYSLTVAVKTL-KEDTMEVEEFLKEAAVMKEIK-HPNLVQLLGVCTLEPP------FYIVTEYMPYGNLLDYLRECNREEVTAVVLLYMATQISSAMEYLE--KKNFIHRDLAARNCLVGENHVVKVADFGLSRLMTGDTYTAHAGA------KFP-IKWTAPESLAY---NTFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYDLLEKGYRMEQPEGCPPKVYELMRACWKWSPADRPSFAE----THQAF*
>P1;AAK1_HUMAN_D0_4WSQ_A
structureX:AAK1_HUMAN_D0_4WSQ_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VTVDEVLAEGGFAIVFL-VRTSNGMKCALKRMFVNNEHDLQVCKREIQIMRDLSGHKNIVGYIDSSINNVSSGDVWEVLILMDFCRGGQVVNLMNQRLQTGFTENEVLQIFCDTCEAVARLHQCKTPIIHRDLKVENILLHDRGHYVLCDFGSATNKFQNPQTEGVNAVEDEIKKYTTLSYRAPEMVNLYSGKIITTKADIWALGCLLYKLCYFTL-PFGESQVA----ICDGNFTIPDNSRYSQDMHCLIRYMLEPDPDKRPDIYQVSYFSFKLL*
