Target-template alignment
>P1;ALK_HUMAN_D0
sequence:ALK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITLIRGLGHGAFGEVYEGQVSGMPNDPSPLQVAVKTLPEVCSEQDELDF-------LMEALIISKFNHQN--IVRCIGVSLQSLPRF-ILLELMAGGDLKSFLRETRPRPSQPSSLAMLDLLHVARDIACGCQYLEENHFIHRDIAARNCLLTCPGPGRVAKIGDFGMARDIYRASYYRKGGCAMLPVKWMPPEAFMEGI-FTSKTDTWSFGVLLWEIFSLGYMPYPSKSNQEVLEF--VTSGGRMDPPKNCPGPVYRIMTQCWQHQPEDRPNFAIILERIEYCTQDPDV*
>P1;ARBK1_BOVIN_D0_1OMW_A
structureX:ARBK1_BOVIN_D0_1OMW_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FSVHRIIGRGGFGEVY-----GCRKADTGKMYAMK-----CLDKKRIKMKQGETLALNERIMLSLVSTGDCPFIVCMSYAFHTPDKLSFILDLMNGGDLHYHL-------SQHGVFSEADMRFYAAEIILGLEHMHNRFVVYRDLKPANILLDEHGH---VRISDLGLACDFSKKKPHASVGTH----GYMAPEVLQKGVAYDSSADWFSLGCMLFKLLR-GHSPFRQHKTKDKHEIDRMTLTMAVELPDSFSPELRSLLEGLLQRDVNRR--LGCLGRGAQEVKESPFF*
