Target-template alignment
>P1;EGFR_HUMAN_D0
sequence:EGFR_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
FKKIKVLGSGAFGTVYKGLWIPEGEKVKIPVAIKELREATSPKANKEILDEAYVMASVDNPHVCRLLGICLT------STVQLITQLMPFGCLLDYVREHKDNIGSQYLLNWCVQIAKGMNYLEDRRLVHRDLAARNVLVKTPQHVKITDFGLAKLLGAEEKEYHAEGGKVPIKWMALESILHRI-YTHQSDVWSYGVTVWELMTFGSKPYDGIPASEISSILEKGERLPQPPICTIDVYMIMVKCWMIDADSRPKFRELIIEFSKMARDPQR----------------YL*
>P1;ARBK1_BOVIN_D0_1OMW_A
structureX:ARBK1_BOVIN_D0_1OMW_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FSVHRIIGRGGFGEVY-GCRKADTGKM-YAMKCLDKKRIKMKQGETLALNERIMLSLVSTGD-CPFI-VCMSYAFHTPDKLSFILDLMN-GGDLHYHLSQHGVFSEADMRFYAAEIILGLEHMHNRFVVYRDLKPANILLDEHGHVRISDLGLA--CDFSKKKPHASVGTH--GYMAPEVLQKGVAYDSSADWFSLGCMLFKLLR-GHSPFRQHKTKDKHEI----DRM------TLTMAVELPDSF------SPELRSLLEGL--LQRDVNRRLGCLGRGAQEVKESPFF*
