Target-template alignment
>P1;EGFR_HUMAN_D0
sequence:EGFR_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
FKKIKVLGSGAFGTVY------------KGLWIPEGEKVKIPVAIKELREATSPKANKEILDEAYVMASVDNP------HVCRLLGICLTSTV-QLITQLMPFGCLLDYVREHKDNIGSQYLLNWCVQIAKGMNYLEDRR--LVHRDLAARNVLVKTPQHVKITDFGLA------------KLLGAEEKEYHAEGGKVPIKWMALESILHRIYTHQSDVWSYGVTVWELMTFGSKPYDGIPASEISSILEKGE-RLPQPPICTIDVYMIMVKCWMIDADSRPKFREL-IIEFSKMARDPQRYL*
>P1;AAK1_HUMAN_D0_4WSQ_A
structureX:AAK1_HUMAN_D0_4WSQ_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VTVDEVLAEGGFAIVFLVRTSNGMKCALKRMFV--NNEHDLQVCKREIQIMRDLSGHKNIV--GYIDSSINNVSSGDVWEVLILMDFCRGGQVVNLMNQRLQTG--------FTENEVLQIFCDTCEAVAR----LHQCKTPIIHRDLKVENILLHDRGHYVLCDFGSATNKFQNPQTEGVNAVEDEIKKYTTLSYRAP-EMVNLYS--GKIITTKADIWALGCLLYKLCYFT------LPFGESQVAICDGNFTIPDNSRYSQDMHCLIRYMLEPDPDKRPDIYQVSYFSF--------KLL*
