Target-template alignment
>P1;SRC_HUMAN_D0
sequence:SRC_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRLEVKLGQGCFGEVWMGTWNGTTRVAIKTLKPGTMSPEAFLQEAQVMKK--LRHEKLVQLYAV-----VSEEPIYIVTEYMSKGSLLDFLKGETGKYLRLPQL-VDMAAQIASGMAYVE--------RMNYVHRDLRAANILVGENLVCKVADFGLARL-IEDNEY-----TARQGAKFPIKWTAPE-------AALYGRFTIKSDVWSFGILLTELTTKGRVPYPGMVNREVLDQVERGYRMP------------------C----PPECPE---------SLHDLMCQCWRKEPEERPTFEYLQAFLEDYF*
>P1;ACVL1_HUMAN_D0_3MY0_A
structureX:ACVL1_HUMAN_D0_3MY0_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VALVECVGKGRYGEVWRGLWHGES-VAVKIF--SSRDEQSWFRETEIYNTVLLRHDNILGFIASDMTSRNSSTQLWLITHYHEHGSLYDFLQRQTLE----PHLALRLAVSAACGLAHLHVEIFGTQGKPAIAHRDFKSRNVLVKSNLQCCIADLGLAVMHSQGSDYLDIGNNPRVGTK---RYMAPEVLDEQIRTDCFESYKW-TDIWAFGLVLWEIA-----------RRTIVNGIVEDYRPPFYDVVPNDPSFEDMKKVVCVDQQTPTIPNRLAADPVLSGLAQMMRECWYPNPSARLTALRIKKTLQK-I*
