Target-template alignment
>P1;ERBB2_HUMAN_D0
sequence:ERBB2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRKVKVLGSGAFGTVYKGIWIPDGENVKIPVAIKVLRENTSPKANK--EILDEAYVMAGVGSPYVSRLL-------GICLTSTVQLVTQLMPY---GCLLDHVRENRGRLGSQDLLNWC-MQIAKGMSYLEDVR-LVHRDLAARNVLVKSPNHVKITDFGLARLLDIDETEYHADGGKVPI-----KWMALESILRRRFTHQSDVWSYGVTVWELMTFGAKPYDGIPAREIPDLLEKGE-RLPQPPICTIDVYMIMVKCWMIDSECRPRFRELVSEFSRMARDPQ----------------RFV*
>P1;AKT1_HUMAN_D0_3CQU_A
structureX:AKT1_HUMAN_D0_3CQU_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FEYLKLLGKGTFGKV---ILVKEKATGRY-YAMKILKKEVIVAKDEVAHTLTENRVLQNSRHPFLTALKYSFQTHDRLCF---------VMEYANGGELFFHL--SRERVFSEDRARFYGAEIVSALDYLHSEKNVVYRDLKLENLMLDKDGHIKITDFGLCK-------EGIKDGATMKTFCGTPEYLAPEVLEDNDYGRAVDWWGLGVVMYEMMC-GRLPFYNQDHEKLFELILMEEIRFPRT--------------------LGPEAKSLLSGL--LKKDPKQRLGGGSEDAKEIMQHRFF*
