Target-template alignment
>P1;ABL2_HUMAN_D0
sequence:ABL2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITMKHKLGGGQYGEVYVGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEIKHPNLVQLLGVCTLEPPFYIVTEY--------------MPYGNLLDYLRECNREEVTAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHVVKVADFGLSRLMTGDTYTAHAGAKFPIKWTAPESLAYN-TFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYDL--LEKGYRMEQPEGCPPKVYELMRA-----------CWKWSPADRPSFAETHQAF*
>P1;ARBK1_BOVIN_D0_1OMW_A
structureX:ARBK1_BOVIN_D0_1OMW_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FSVHRIIGRGGFGEVYGCRKADTGKMYAMKCLDKKRIKMKQ--GETLALNERIMLSLVST-GDC----PFIVCMSYAFHTPDKLSFILDLMNGGDLHYHLSQ--HGVFSEADMRFYAAEIILGLEHMHNRFVVYRDLKPANILLDEHGHVRISDLGLACDFSKKKPHASVGTH---GYMAPEVLQKGVAYDSSADWFSLGCMLFKLLR-GHSPFRQHKTKDKHEIDRMTLTMAVELPDSFSPELRSLLEGLLQRDVNRRLGCLGRGAQE----VKESPFF*
