Target-template alignment
>P1;CSK_HUMAN_D0
sequence:CSK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LKLLQTIGKGEFGDVML-GDYRGNKVAVK--CIKNDATAQAFLAEASVMTQLR-HSNLVQLLGVIVEE--KGGLY---IVTEYMAKGSLVDYLRSRGRSVLGGDCLLKFSLDVCEAMEYLEG--NNFVHRDLAARNVLVSEDNVAKVSDFG-LTKEASSTQDTGKLPVK----------WTAPEALR---EKKFSTKSDVWSFGILLWEIYSFGRVPYPRIPLKDVVPRVEKGYKMDAPDGCPPAVYEVMKNCWHLDAAMRPSFLQLREQLEHIKTHELH*
>P1;AAK1_HUMAN_D0_4WSQ_A
structureX:AAK1_HUMAN_D0_4WSQ_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VTVDEVLAEGGFAIVFLVRTSNGMKCALKRMFVNNEHDLQVCKREIQIMRDLSGHKNIVGYIDSSINNVSSGDVWEVLILMDFCRGGQVVNLMNQRLQTGFTENEVLQIFCDTCEAVARLHQCKTPIIHRDLKVENILLHDRGHYVLCDFGSATNKFQNPQTEGVNAVEDEIKKYTTLSYRAPEMVNLYSGKIITTKADIWALGCLLYKLCYF-TLPFG----ESQVAICDGNFTIPDNSRYSQDMHCLIRYMLEPDPDKRPDIYQVS-----YFSFKLL*
