Target-template alignment
>P1;SRC_HUMAN_D0
sequence:SRC_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRLEVKLGQGCFGEVWM-GTWNGTTRVAIKTLKPGTMSPEAFLQEAQVMKKLR-HEKLV-----QLYAVVSEE--PIYIVTEYMSKGSLLDFLKGETGKYLRLPQLVDMAAQIASGMAYVERMN--YVHRDLRAANILV---GENLVCKVADFGLA------------RLIEDN--EYTARQGAKFPIKWTAPE-AALY-GRF-TIKSDVWSFGILLTELTTKGRVPYPGMVNREVLDQVERGYRMPCPPECPESLHDLMCQCWRKEPEERPTFEYLQAFLEDYF*
>P1;AAK1_HUMAN_D0_4WSQ_A
structureX:AAK1_HUMAN_D0_4WSQ_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VTVDEVLAEGGFAIVFLVRTSNGMKCALKRMFVNNEHDLQVCKREIQIMRDLSGHKNIVGYIDSSINNVSSGDVWEVLILMDFCRGGQVVNLMNQRLQTGFTENEVLQIFCDTCEAVARLHQCKTPIIHRDLKVENILLHDRGHYVLC---DFGSATNKFQNPQTEGVNAVEDEIKKYTT-------LSYRAPEMVNLYSGKIITTKADIWALGCLLYKLCYF-TLPF----GESQVAICDGNFTIPDNSRYSQDMHCLIRYMLEPDPDKRPDIYQVSYFSFKLL*
