Target-template alignment
>P1;EGFR_HUMAN_D0
sequence:EGFR_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
FKKIKVLGSGAFGTVYKGLWIPEGEKVKIPVAIKELREATSPKANKEILDEAYVMASVDNPHVCRLLGICLTSTVQLITQLMPFGCLLDYVREHKDNI--------GSQYLLN--------------WCVQIAKGMNYLE-DRRLVHRDLAARNVLVKTPQHVKITDFGLAK---LLGAEEKEYHAEGGKVPIKWMALESILHRIYTHQSDVWSYGVTVWELMTFGSKPYDGIPASEI-SSILEKGERLPQPPICTIDVYMIMVKCWMIDADSRPKF-------RELIIEFSKMARDPQRYL*
>P1;AKT1_HUMAN_D0_3CQU_A
structureX:AKT1_HUMAN_D0_3CQU_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FEYLKLLGKGTFGKV---------------ILVKE--KATGRYYAMKILKKEVIVAKDEVAHT-------LTENRVLQNSRHPFLTALKYSFQTHDRLCFVMEYANGGELFFHLSRERVFSEDRARFYGAEIVSALDYLHSEKNVVYRDLKLENLMLDKDGHIKITDFGLCKEGIKDGATMKTFCGTP-----EYLAPEVLEDNDYGRAVDWWGLGVVMYEMMC-GRLPFYNQDHEKLFELILMEEIRFPR----TLGPEAKSLLSGLLKKDPKQRLGGGSEDAKEIM---------QHRFF*
