Target-template alignment
>P1;ABL1_HUMAN_D0
sequence:ABL1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITMKHKLGGGQYGEVY----EGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQEVNAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSR--LMTGDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYELLEKDYRMERPEGCPEKVYELMRACWQWNPSDR----PSFAEIHQAFETMFQESSISDEVEKELGKQ*
>P1;AKT2_HUMAN_D0_1GZK_A
structureX:AKT2_HUMAN_D0_1GZK_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FDYLKLLGKGTFGKVILVREKATGRYYAMKILRKEVIIAKDEVAHTVTESRVLQNTRHPFLTALKYAFQTHDRLCFVMEYANGGEL--FFHLSRERVFTEERARFYGAEIVSALEYLHSRDVVYRDIKLENLMLDKDGHIKITDFGLCKEGISDGATMKTFCGTP---EYLAPEVLEDNDYGRAVDWWGLGVVMYEM-MCGRLPFYNQDHERLFELILME-EIRFPRTLSPEAKSLLAGLLKKDPKQRLGGGPS--DAKEVMEHRF---------------F*
