Target-template alignment
>P1;EGFR_HUMAN_D0
sequence:EGFR_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
FKKIKVLGSGAFGTVYKGLWIPEGEKVKIPVAIKELREATSPKANKEILDEAYVMASVDNPHVCRLLGICLTSTVQLITQLMPFGCLLDYVREHKDNI--------GSQYLLN--------------WCVQIAKGMNYLEDRRLVHRDLAARNVLVKTPQHVKITDFGLAKLLGAEEKEYHAEGGKVPI-----KWMALESILHRIYTHQSDVWSYGVTVWELMTFGSKPYDGIPASEI-SSILEKGERLPQPPICTIDVYMIMVKCWMIDADSRPKFRELIIEFSKMARDPQ----------------RYL*
>P1;AKT2_HUMAN_D0_1GZK_A
structureX:AKT2_HUMAN_D0_1GZK_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FDYLKLLGKGTFGKV---------------ILVRE--KATGRYYAMKILRKEVIIAKDEVAHT-------VTESRVLQNTRHPFLTALKYAFQTHDRLCFVMEYANGGELFFHLSRERVFTEERARFYGAEIVSALEYLHSRDVVYRDIKLENLMLDKDGHIKITDFGLCK-------EGISDGATMKTFCGTPEYLAPEVLEDNDYGRAVDWWGLGVVMYEMMC-GRLPFYNQDHERLFELILMEEIRFPRT--------------------LSPEAKSLLAGL--LKKDPKQRLGGGPSDAKEVMEHRFF*
