Target-template alignment
>P1;ALK_HUMAN_D0
sequence:ALK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITLIRGLGHGAFGEVYEGQVSGMPNDPSPLQVAVKTLPEVCSEQDELDFLMEALIISK--FNHQNIVRCIGVSLQSLPR----FILLELMAGGDLKSFLRETRPRPSQPSSLAMLDLLHVARDIACGCQYLEENHF--------IHRDIAARNCL----LTCPGPGRVAKIGDFGMA-RDIYRASYYRKGGCAMLPVK-WMPPEAFMEGI----FTSK--TDTWSFGVLLWEI--------FSLGYMP--Y------PSKSNQEVLEFVTSGGRMDPPKNCPGPVY----RIMTQCWQHQPEDRPNFAIILERIEYCTQDPDV*
>P1;ACVL1_HUMAN_D0_3MY0_A
structureX:ACVL1_HUMAN_D0_3MY0_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VALVECVGKGRYGEVWRGLWHGES-------VAVK----IFSSRDEQSWFRETEIYNTVLLRHDNILGFIASDMTSRNSSTQLWLITHYHEHGSLYDFLQRQTLEPHLA--------LRLAVSAACGLAHLHVEIFGTQGKPAIAHRDFKSRNVLVKSNLQC-------CIADLGLAVMHSQGSDYLDIGNNPRVGTKRYMAPEVLDEQIRTDCFESYKWTDIWAFGLVLWEIARRTIVNGIVEDYRPPFYDVVPNDPSFEDMKKVVCVDQQTPTIPNRLAADPVLSGLAQMMRECWYPNPSARLTALRIKKTLQ------KI*
