Target-template alignment
>P1;ABL2_HUMAN_D0
sequence:ABL2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITMKHKLGGGQYGEVYVGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEI--KHPNLVQLLGV----CTLEPPFYIVTEYMPYGNLLDYLRECNREEVTAVVLLYMATQISSAMEYLEKKNF--------IHRDLAARNCLVGENHVVKVADFGLSRLMT-GDTY-----TAHAGAKFPIKWTAPESL-------AYNTFSIKSDVWAFGVLLWEIA----------TYGMSPYPGIDLSQVYDLLEKGYRMEQPEGCPPK----------VYELMRACWKWSPADRPS---FAETHQAF*
>P1;ACVL1_HUMAN_D0_3MY0_A
structureX:ACVL1_HUMAN_D0_3MY0_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VALVECVGKGRYGEVWRGLWHGESVAVKIFSSRDE----QSWFRETEIYNTVLLRHDNILGFIASDMTSRNSSTQLWLITHYHEHGSLYDFLQ---RQTLEPHLALRLAVSAACGLAHLHVEIFGTQGKPAIAHRDFKSRNVLVKSNLQCCIADLGLAVMHSQGSDYLDIGNNPRVGTK---RYMAPEVLDEQIRTDCFESYKW-TDIWAFGLVLWEIARRTIVNGIVEDYRPPFYDVVPNDPSFEDMKKVVCVDQQTPTIPNRLAADPVLSGLAQMMRECWYPNPSARLTALRIKKTLQKI*
