Target-template alignment
>P1;SRC_HUMAN_D0
sequence:SRC_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRLEVKLGQGCFGEVWMGTWNGTTRV-AIKTLKPGTMSPEA----FLQEAQVMKKLRHEKLVQL-YAVVSEEPIYIVTEYMSKGSLL------DFLKGETGKYLRLPQLVDMAAQIASGMAYVE-RMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNEYTARQGAKFPI-----KWTAPEAALYGRFTIKSDVWSFGILLTELTTKGRVPYPGMVNREVLDQV---ERGYRMPCPPECPESLHDLMCQCWRKEPEER---PTFEYLQAFLEDYF*
>P1;AKT1_HUMAN_D0_3CQU_A
structureX:AKT1_HUMAN_D0_3CQU_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FEYLKLLGKGTFGKVILVKEKATGRYYAMKILKKEVIVAKDEVAHTLTENRVLQNSRHPFLTALKYSFQTHDRLCFVMEYANGGELFFHLSRERVFSEDRARFY--------GAEIVSALDYLHSEKNVVYRDLKLENLMLDKDGHIKITDFGLCK------EGIKDGATMKTFCGTPEYLAPEVLEDNDYGRAVDWWGLGVVMYEMMC-GRLPFYNQDHEKLFELILMEEIRFPRTLGPEAKSLLSGLL----KKDPKQRLGGGSEDAKEIMQHRFF*
