Target-template alignment
>P1;ABL1_HUMAN_D0
sequence:ABL1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITMKHKLGGGQYGEVYEGVWKKYSLTVAVKTL-KEDTMEVEEFLKEAAVMKEIK-HPNLVQLLGVCTREPP------FYIITEFMTYGNLLDYLRECNRQEVNAVVLLYMATQISSAMEYLE--KKNFIHRDLAARNCLVGENHLVKVADFGLSRLMTGDTYTAHAGA------KFP-IKWTAPESLAYNK---FSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYELLEKDYRMERPEGCPEKVYELMRACWQWNPSDRPSFAEI-HQAFETMFQESSISDEVEKELGKQ*
>P1;AAK1_HUMAN_D0_4WSQ_A
structureX:AAK1_HUMAN_D0_4WSQ_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VTVDEVLAEGGFAIVFL-VRTSNGMKCALKRMFVNNEHDLQVCKREIQIMRDLSGHKNIVGYIDSSINNVSSGDVWEVLILMDFCRGGQVVNLMNQRLQTGFTENEVLQIFCDTCEAVARLHQCKTPIIHRDLKVENILLHDRGHYVLCDFGSATNKFQNPQTEGVNAVEDEIKKYTTLSYRAPEMVNLYSGKIITTKADIWALGCLLYKLCYFTL-PFGESQVA----ICDGNFTIPDNSRYSQDMHCLIRYMLEPDPDKRPDIYQVSYFSFKLL-----------------*
