Target-template alignment
>P1;ALK_HUMAN_D0
sequence:ALK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITLIRGLGHGAFGEVYEGQVSGMPNDPSPLQVAVKTLPEVCSEQDELDFLMEALIISK--FNHQNIVRCIGVSLQSLPR----FILLELMAGGDLKSFLRETRPRPSQPSSLAMLDLLHVARDIACGCQYLEENHF--------IHRDIAARNCLLTCPGPGRVAKIGDFGMA-------RDIYRASYYRKGGCAMLPVKWMPPEAFMEGI----FTS--KTDTWSFGVLLWEI--------FSLGYMP-----YPSKSNQEVLEFVTSGGRMDPPKNCPGPVY---------RIMTQCWQHQPEDRPNFAIILERIEYCTQDPDV*
>P1;ACVR1_HUMAN_D0_3H9R_A
structureX:ACVR1_HUMAN_D0_3H9R_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
ITLLECVGKGRYGEVWRGSWQGE-------NVAVK----IFSSRDEKSWFRETELYNTVMLRHENILGFIASDMTSRHSSTQLWLITHYHEMGSLYDYL--------QLTTLDTVSCLRIVLSIASGLAHLHIEIFGTQGKPAIAHRDLKSKNILVKKNGQ---CCIADLGLAVMHSQSTNQLDVGNNPRVG-----TKRYMAPEVLDETIQVDCFDSYKRVDIWAFGLVLWEVARRMVSNGIVEDYKPPFYDVVPNDPSFEDMRKVVCVDQQRP--NIPNRWFSDPTLTSLAKLMKECWYQNPSAR----LTALRIKKTLTKID-*
