Target-template alignment
>P1;ALK_HUMAN_D0
sequence:ALK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITLIRGLGHGAFGEVYEGQVSGMPNDPSPLQVAVKTL-PEVCSEQDELDFLMEALIISKFNHQNIVRCIGVSLQSLPRF-ILLELMAGGDLKSFLRETRPRPSQPSSLAMLDLLHVARDIACGCQYLEENHFIHRDIAARNCLLTCPGPGRVAKIGDFGMARDIYRASYYRKGGCAMLPVKWMPPEAFMEGIFTSKTDTWSFGVLLWEIFSLGYMPYPSKSNQEVLEFVTSGGRMDPPKNCPGPVYRIMTQCWQHQPEDR----PNFAIILERIEYCTQDPDV*
>P1;AKT2_HUMAN_D0_1GZK_A
structureX:AKT2_HUMAN_D0_1GZK_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FDYLKLLGKGTFGKVIL-----VREKATGRYYAMKILRKEVIIAKDEVAHTVTESRVLQNTRHPFLTALKYAFQTHDRLCFVMEYANGGEL--FFHLSRERVFTEERARFY-----GAEIVSALEYLHSRDVVYRDIKLENLMLDKDGH---IKITDFGLCKEGISDGATMKTFCG--TPEYLAPEVLEDNDYGRAVDWWGLGVVMYEMMC-GRLPFYNQDHERLFELILME-EIRFPRTLSPEAKSLLAGLLKKDPKQRLGGGPSDAKEVMEHRF------F*
