Target-template alignment
>P1;CSK_HUMAN_D0
sequence:CSK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LKLLQTIGKGEFGDVMLGDYRGNKVAVKCIKNDATAQAFLAEASVMTQ--LRHSNLVQLLGVIVEEKGG---LYIVTEYMAKGSLVDYLRSRGRSVLGGDCLLKFSLDVCEAMEYLEGNNF--------VHRDLAARNVLVSEDNVAKVSDFGLT---KEASSTQDTGKLP----VKWTAPEALREKK----FSTK--SDVWSFGILLWEI----YSFGRVPYPRIPLKDVVPR---VEKGYKMDAPDGCPPAV-------------YEVMKNCWHLDAAMRPSFLQLREQLEHIKTHELH*
>P1;ACVL1_HUMAN_D0_3MY0_A
structureX:ACVL1_HUMAN_D0_3MY0_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VALVECVGKGRYGEVWRGLWHGESVAVK-IFSSRDEQSWFRETEIYNTVLLRHDNILGFIASDMTSRNSSTQLWLITHYHEHGSLYDFLQ---RQTLEPHLALRLAVSAACGLAHLHVEIFGTQGKPAIAHRDFKSRNVLVKSNLQCCIADLGLAVMHSQGSDYLDIGNNPRVGTKRYMAPEVLDEQIRTDCFESYKWTDIWAFGLVLWEIARRTIVNGIVEDYRPPFYDVVPNDPSFEDMKKVVCVDQQTPTIPNRLAADPVLSGLAQMMRECWYPNPSARLTALRIKKTLQKI------*
