Target-template alignment
>P1;EGFR_HUMAN_D0
sequence:EGFR_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
FKKIKVLGSGAFGTVYKGLWIPEGEKVKIPVAIKELREATSPKANKEILDEAYVMASVDNPHVCRLLGICLT--------STVQLITQLMPFGCLLDYVREHKDNIGSQYLLNWCVQIAKGMNYLE--------DRRLVHRDLAARNVLVKTPQHVKITDFGLAKLLGAEEKEYHAEGGKVPI---KWMALESILHRIYTHQ------SDVWSYGVTVWELM----------TFGSKPYDGIPAS----EISSILEKGE-------RLPQPPICTIDVYMIMVKCWMIDADSRPKFRELIIEFSKMARDPQRYL*
>P1;ACVL1_HUMAN_D0_3MY0_A
structureX:ACVL1_HUMAN_D0_3MY0_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VALVECVGKGRYGEVWRGLW--HGESV--AVKIFSSRDEQSWFRETEIYNT--VLLRHDN-----ILGFIASDMTSRNSSTQLWLITHYHEHGSLYDFLQ--RQTLEPHLALRLAVSAACGLAHLHVEIFGTQGKPAIAHRDFKSRNVLVKSNLQCCIADLGLA-VMHSQGSDYLDIGNNPRVGTKRYMAPEVLDEQIRTDCFESYKWTDIWAFGLVLWEIARRTIVNGIVEDYRPPFYDVVPNDPSFEDMKKVVCVDQQTPTIPNRLAADPVLS-GLAQMMRECWYPNPSAR-------LTALRIKKTLQK-I*
