Target-template alignment
>P1;ERBB2_HUMAN_D0
sequence:ERBB2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRKVKVLGSGAFGTVYKGIWIPDGENVKIPVAIKVLRENT--SPKANKEILDEAYVMAGVGSPYVSRLL-------GICLTSTVQLVTQLMPY---GCLLDHVR------ENRGRLGSQDLLNWCMQIAKGMSYLEDVRLVHRDLAARNVLVKSPNHVKITDFGLARLLDIDETEYHADGGKVPI-----KWMALESILRRRFTHQSDVWSYGVTVWELMTFGAKPYDGIPAREIPDLLEKGE-RLPQPPICTIDVYMIMVKCWMIDSECRPRFRELVSE--FSRMARDP--------QRFV*
>P1;AKT2_HUMAN_D0_1GZK_A
structureX:AKT2_HUMAN_D0_1GZK_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FDYLKLLGKGTFGKV---ILVREKATGRY-YAMKILRKEVIIAKDEVAHTVTESRVLQNTRHPFLTALKYAFQTHDRLCF---------VMEYANGGELFFHLSRERVFTEERARF-------YGAEIVSALEYLHSRDVVYRDIKLENLMLDKDGHIKITDFGLCK-------EGISDGATMKTFCGTPEYLAPEVLEDNDYGRAVDWWGLGVVMYEMMC-GRLPFYNQDHERLFELILMEEIRFPRT----------------LSPEAKSLLAGLLKKDPKQRLGGGPSDAKEVMEHRFF*
