Target-template alignment
>P1;SRC_HUMAN_D0
sequence:SRC_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRLEVKLGQGCFGEVWMGTWNGTTRVAIKTLKPGTMSPEAFLQEAQVMKK--LRHEKLVQLYAV-----VSEEPIYIVTEYMSKGSLLDFLKGETGKYLRLPQLVDMAAQIASGMAYVE--------RMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNEYTARQGAKFPI---KWTAPEA-------ALYGRFTIKSDVWSFGILLTELTTKGRVPYPGMVNREVLDQVERGY--------------RMPC----PPECPE---------SLHDLMCQCWRKEPEERPTFEYLQAFLEDYF*
>P1;ACVR1_HUMAN_D0_3H9R_A
structureX:ACVR1_HUMAN_D0_3H9R_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
ITLLECVGKGRYGEVWRGSWQGEN-VAVKIF--SSRDEKSWFRETELYNTVMLRHENILGFIASDMTSRHSSTQLWLITHYHEMGSLYDYLQLTT---LDTVSCLRIVLSIASGLAHLHIEIFGTQGKPAIAHRDLKSKNILVKKNGQCCIADLGLAVMHSQSTNQLDVGNNPRVGTKRYMAPEVLDETIQVDCFDSYK-RVDIWAFGLVLWEVARR-------MVSNGIVEDYKPPFYDVVPNDPSFEDMRKVVCVDQQRPNIPNRWFSDPTLTSLAKLMKECWYQNPSARLTALRIKKTLTKID*
