Target-template alignment
>P1;ABL1_HUMAN_D0
sequence:ABL1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITMKHKLGGGQYGEVYEGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEI--KHPNLVQLLG--VCTREPP--FYIITEFMTYGNLLDYLRECNRQEVNAVVLLYMATQISSAMEYLEKKNF--------IHRDLAARNCLVGENHLVKVADFGLSRLMTGDTYTAHAGAKFPI---KWTAPESL-------AYNKFSIKSDVWAFGVLLWEIA----TYGM-----SPYPGIDLSQVYELLEKDYRME-----------RPEGCPEKVY---------ELMRACWQWNPSDRPSFAEIHQAFETMFQESSISDEVEKELGKQ*
>P1;ACVR1_HUMAN_D0_3H9R_A
structureX:ACVR1_HUMAN_D0_3H9R_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
ITLLECVGKGRYGEVWRGSWQGENVAVKIFSSRDE----KSWFRETELYNTVMLRHENILGFIASDMTSRHSSTQLWLITHYHEMGSLYDYLQ---LTTLDTVSCLRIVLSIASGLAHLHIEIFGTQGKPAIAHRDLKSKNILVKKNGQCCIADLGLAVMHSQSTNQLDVGNNPRVGTKRYMAPEVLDETIQVDCFDSYK-RVDIWAFGLVLWEVARRMVSNGIVEDYKPPF--------YDVVPNDPSFEDMRKVVCVDQQRPN-IPNRWFSDPTLTSLAKLMKECWYQNPSARLTALRIKKTLTKI----------------D*
