Target-template alignment
>P1;ALK_HUMAN_D0
sequence:ALK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITLIRGLGHGAFGEVYEGQVSGMPNDPSPLQVAVKTLPEVCSEQDELDFLMEALIISK--FNHQNIVRCIGVSLQSLPR------FILLELMAGGDLKSFLRETRPRPSQPSSLAMLDLLHVARDIACG-CQYLEENH-----FIHRDIAARNCLLTCPGPGRVAKIGDFGMARDIYRASYYRKGGCAML--------PVKWMPPEA---FMEGIFTSKTDTWSFGVLLWEIFSLGYMPYPSKSNQEVLEFVTSGGRMDPPKNC--PGPVYRIMTQCWQHQPEDRPNFAIILERIEYCTQDPDV*
>P1;AAK1_HUMAN_D0_4WSQ_A
structureX:AAK1_HUMAN_D0_4WSQ_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VTVDEVLAEGGFAIVF------LVRTSNGMKCALKRM--FVNNEHDLQVCKREIQIMRDLSGHKNIVGYIDSSINNVSSGDVWEVLILMDFCRGGQVVNLMNQR-----LQTGFTENEVLQ----IFCDTCEAVARLHQCKTPIIHRDLKVENILLHDRGH---YVLCDFGSATNKFQNP--QTEGVNAVEDEIKKYTTLSYRAPEMVNLYSGKIITTKADIWALGCLLYKLC---YFTLPFGESQVAI----CDGNFTIPDNSRYSQDMHCLIRYMLEPDPDKRPD----IYQVSYFSFKL-L*
