Target-template alignment
>P1;ALK_HUMAN_D0
sequence:ALK_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITLIRGLGHGAFGEVYEGQVSGMPNDPSPLQVAVKTLP-EVCSEQDELDFLMEALIISKFNHQNIVRCIGVSLQSLPRF-ILLELMAGGDL------KSFLRETRPRPSQPSSLAMLDLLHVARDIACGCQYLEENHFIHRDIAARNCLLTCPGPGRVAKIGDFGMARDIYRASYYRKGGCAMLPVKWMPPEAFMEGIFTSKTDTWSFGVLLWEIFSLGYMPYPSKSNQEVLEFVTSGGRMDPPKNCPGPVYRIMTQCWQHQPEDR------PNFAIILERIEYCTQDPDV*
>P1;AKT1_HUMAN_D0_3CQU_A
structureX:AKT1_HUMAN_D0_3CQU_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FEYLKLLGKGTFGKVIL-----VKEKATGRYYAMKILKKEVIVAKDEVAHTLTENRVLQNSRHPFLTALKYSFQTHDRLCFVMEYANGGELFFHLSRERVFSEDRARFYGAEIVSALDYLHSEKNV------------VYRDLKLENLMLDKDGH---IKITDFGLCKEGIKDGATMKTFCG--TPEYLAPEVLEDNDYGRAVDWWGLGVVMYEMMC-GRLPFYNQDHEKLFELILME-EIRFPRTLGPEAKSLLSGLLKKDPKQRLGGGSEDAKEIMQHRF--------F*
