Target-template alignment
>P1;ERBB2_HUMAN_D0
sequence:ERBB2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRKVKVLGSGAFGTVYKGIWIPDGENVKIPVAIKVLRENTSPK-------ANKEILDEAYVMAGVGSPYVSRLLGICLTSTVQLVTQLMPYGCLLDHVRENRGRLGSQDLLNWCMQIAKGMSYLE--------DVRLVHRDLAARNVLVKSPNHVKITDFGLARLLDIDETEYHADGGKVPI---KWMALESILRRRFTHQ-------SDVWSYGVTVWELM----------TFGAKPYDGIPA--------------REIPDLLEKGERLPQPPICTIDVYMIMVKCWMIDSECRPRFRELVSEFSRMARDPQRFV*
>P1;ACVL1_HUMAN_D0_3MY0_A
structureX:ACVL1_HUMAN_D0_3MY0_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VALVECVGKGRYGEVWRGLW--HGESV----AVKIFSSRDEQSWFRETEIYNTVLLRHDNILGFIASDMTSR----NSSTQLWLITHYHEHGSLYDFLQ--RQTLEPHLALRLAVSAACGLAHLHVEIFGTQGKPAIAHRDFKSRNVLVKSNLQCCIADLGLA-VMHSQGSDYLDIGNNPRVGTKRYMAPE-VLDEQIRTDCFESYKWTDIWAFGLVLWEIARRTIVNGIVEDYRPPFYDVVPNDPSFEDMKKVVCVDQQTPTI---PNRLAADPVLS-GLAQMMRECWYPNPSAR--LTAL-----RIKKTLQK-I*
