Target-template alignment
>P1;ABL2_HUMAN_D0
sequence:ABL2_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
ITMKHKLGGGQYGEVYVGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEI--KHPNLVQLLGV----CTLEPPFYIVTEYMPYGNLLDYLRECNREEVTAVVLLYMATQISSAMEYLEKKNF--------IHRDLAARNCLVGENHVVKVADFGLSRLMTGDTYTAHAGAKFPI---KWTAPESL-------AYNTFSIKSDVWAFGVLLWEIA----------TYGMSPYPGIDLSQVYDLLEKGYRMEQPEGCPPKVY----------ELMRACWKWSPADRPSFAETHQAF----*
>P1;ACVR1_HUMAN_D0_3H9R_A
structureX:ACVR1_HUMAN_D0_3H9R_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
ITLLECVGKGRYGEVWRGSWQGENVAVKIFSSRDE----KSWFRETELYNTVMLRHENILGFIASDMTSRHSSTQLWLITHYHEMGSLYDYLQLTTLDTVSCLRIVL---SIASGLAHLHIEIFGTQGKPAIAHRDLKSKNILVKKNGQCCIADLGLAVMHSQSTNQLDVGNNPRVGTKRYMAPEVLDETIQVDCFDSYK-RVDIWAFGLVLWEVARRMVSNGIVEDYKPPFYDVVPNDPSFEDMRKVVCVDQQRPNIPNRWFSDPTLTSLAKLMKECWYQNPSARLTALRIKKTLTKID*
