Target-template alignment
>P1;SRC_HUMAN_D0
sequence:SRC_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
LRLEVKLGQGCFGEVWMGTWNGTTRVAIKTLKPGTMSPEAFLQEAQVMKKLRHEKLVQL---------------------YAVVSEEPIYIVTEYMSKGSLLDFLKGETGKY----LRLPQLVDMAAQIASGMAYVERMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNEYTARQGAKFPIKWTAPEAALYG-RFTIKSDVWSFGILLTELTTKGRVPYPGMVNREV--LDQVERGYRMPCPPECPESLHDLMCQCWRKEPEERPTFEYLQAFLED-----YF*
>P1;ARBK1_BOVIN_D0_1OMW_A
structureX:ARBK1_BOVIN_D0_1OMW_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
FSVHRIIGRGGFGEVY----------GCRKADTGKMYAMKCLDKKRI--KMKQGETLALNERIMLSLVSTGDCPFIVCMSYAFHTPDKLSFILDLMNGGDL-HYHLSQHGVFSEADMRF-----YAAEIILGLEHMHNRFVVYRDLKPANILLDEHGHVRISDLGLACDFSKKKPHASVGTH---GYMAPEVLQKGVAYDSSADWFSLGCMLFKLL-RGHSPFRQHKTKDKHEIDRMTLTMAVELPDSFSPELRSLLEGLLQRDVNRR--LGCLGRGAQEVKESPFF*
